import streamlit as st
import pandas as pd
import re

# =========================
# PAGE CONFIGURATION
# =========================
st.set_page_config(page_title="PC Parts Comparison", page_icon="📊", layout="wide")

# =========================
# HELPER FUNCTIONS
# =========================
def clean_price(price_str):
    """Convert messy price strings like '1 234,56 MAD' to float 1234.56"""
    if pd.isna(price_str) or not isinstance(price_str, str):
        return None
    # Remove everything except digits, commas, and dots
    cleaned = re.sub(r'[^\d,\.]', '', price_str)
    # Handle French/Arabic decimal comma
    if ',' in cleaned and '.' in cleaned:
        cleaned = cleaned.replace(',', '') # comma is thousands separator
    elif ',' in cleaned:
        cleaned = cleaned.replace(',', '.') # comma is decimal
    try:
        return float(cleaned)
    except ValueError:
        return None

def process_data(df, site_name):
    """Standardize the dataframe for comparison"""
    if df is None or df.empty:
        return pd.DataFrame()
    
    # Keep only necessary columns
    cols = ["categorie", "site", "url_produit", "product_name", "reference", "price", "availability"]
    for col in cols:
        if col not in df.columns:
            df[col] = None
            
    df = df[cols].copy()
    
    # Clean references (remove empty, strip spaces)
    df['reference'] = df['reference'].astype(str).str.strip()
    df = df[df['reference'].notna() & (df['reference'] != '') & (df['reference'] != 'nan')]
    
    # Clean prices
    df['price_num'] = df['price'].apply(clean_price)
    
    # Standardize availability
    df['availability'] = df['availability'].str.lower().apply(
        lambda x: 'In Stock' if 'instock' in str(x) or 'disponible' in str(x) else 'Out of Stock'
    )
    
    df['site'] = site_name
    return df

def merge_data(df1, df2, site1_name, site2_name):
    """Merge two dataframes based on reference"""
    # Rename columns for clarity
    df1_renamed = df1.rename(columns={
        'product_name': f'{site1_name}_name',
        'price_num': f'{site1_name}_price',
        'availability': f'{site1_name}_stock',
        'url_produit': f'{site1_name}_url',
        'categorie': 'categorie' # Keep one category
    })[['reference', 'categorie', f'{site1_name}_name', f'{site1_name}_price', f'{site1_name}_stock', f'{site1_name}_url']]
    
    df2_renamed = df2.rename(columns={
        'product_name': f'{site2_name}_name',
        'price_num': f'{site2_name}_price',
        'availability': f'{site2_name}_stock',
        'url_produit': f'{site2_name}_url'
    })[['reference', f'{site2_name}_name', f'{site2_name}_price', f'{site2_name}_stock', f'{site2_name}_url']]
    
    # Outer merge to keep all products, even exclusives
    merged = pd.merge(df1_renamed, df2_renamed, on='reference', how='outer', suffixes=('', '_drop'))
    
    # Clean up duplicate category column if exists
    if 'categorie_drop' in merged.columns:
        merged['categorie'] = merged['categorie'].fillna(merged['categorie_drop'])
        merged.drop(columns=['categorie_drop'], inplace=True)
        
    # Calculate price difference
    merged['price_diff'] = merged[f'{site1_name}_price'] - merged[f'{site2_name}_price']
    
    # Determine stock status
    def get_stock_status(row):
        s1 = row[f'{site1_name}_stock']
        s2 = row[f'{site2_name}_stock']
        if pd.isna(s1): return f"Only in {site2_name}"
        if pd.isna(s2): return f"Only in {site1_name}"
        if s1 == "In Stock" and s2 == "In Stock": return "Both In Stock"
        if s1 == "Out of Stock" and s2 == "Out of Stock": return "Both Out of Stock"
        if s1 == "In Stock": return f"Only {site1_name} In Stock"
        if s2 == "In Stock": return f"Only {site2_name} In Stock"
        return "Unknown"
        
    merged['stock_status'] = merged.apply(get_stock_status, axis=1)
    
    return merged

# =========================
# UI LAYOUT
# =========================
st.title("📊 PC Parts Price & Stock Comparison")

st.markdown("""
Upload your Excel files generated by the scrapers. Choose a comparison mode from the sidebar to see differences in **Prices** and **Availability** based on product references.
""")

# Sidebar Menu
st.sidebar.header("⚙️ Configuration")
menu_option = st.sidebar.selectbox(
    "Choose Comparison Mode",
    ["ZoneTech vs UltraPC", "ZoneTech vs NextLevelPC"]
)

# Set expected file names based on menu
if menu_option == "ZoneTech vs UltraPC":
    site1, site2 = "ZoneTech", "UltraPC"
else:
    site1, site2 = "ZoneTech", "NextLevelPC"

# File Uploaders
col1, col2 = st.columns(2)
with col1:
    st.subheader(f"📁 {site1} Data")
    file1 = st.file_uploader(f"Upload {site1} Excel", type=["xlsx"], key="file1")
    
with col2:
    st.subheader(f"📁 {site2} Data")
    file2 = st.file_uploader(f"Upload {site2} Excel", type=["xlsx"], key="file2")


# =========================
# DATA PROCESSING & VISUALIZATION
# =========================
if file1 and file2:
    with st.spinner("Processing data..."):
        try:
            # Read files
            df1_raw = pd.read_excel(file1)
            df2_raw = pd.read_excel(file2)
            
            # Process data
            df1 = process_data(df1_raw, site1)
            df2 = process_data(df2_raw, site2)
            
            if df1.empty or df2.empty:
                st.error("One of the files is empty or missing required columns (reference, price, availability).")
            else:
                # Merge
                merged_df = merge_data(df1, df2, site1, site2)
                
                # Sidebar Filters
                st.sidebar.markdown("---")
                st.sidebar.subheader("🔍 Filters")
                
                # Filter by category
                categories = merged_df['categorie'].dropna().unique().tolist()
                selected_cats = st.sidebar.multiselect("Select Categories", categories, default=categories)
                
                # Filter by Stock Status
                stock_statuses = merged_df['stock_status'].unique().tolist()
                selected_stock = st.sidebar.multiselect("Select Stock Status", stock_statuses, default=stock_statuses)
                
                # Apply filters
                filtered_df = merged_df[
                    (merged_df['categorie'].isin(selected_cats)) & 
                    (merged_df['stock_status'].isin(selected_stock))
                ]
                
                # ==========================================
                # DASHBOARD TABS (Different ways to view diff)
                # ==========================================
                tab1, tab2, tab3, tab4 = st.tabs([
                    "📈 Summary & Metrics", 
                    "💰 Price Differences", 
                    "📦 Stock Differences", 
                    "🗂️ Exclusive Products"
                ])
                
                # --- TAB 1: Summary ---
                with tab1:
                    st.header("Summary Metrics")
                    
                    m1, m2, m3, m4 = st.columns(4)
                    m1.metric(f"Total {site1} Products", len(df1))
                    m2.metric(f"Total {site2} Products", len(df2))
                    m3.metric("Common Products (By Ref)", len(merged_df.dropna(subset=[f'{site1}_name', f'{site2}_name'])))
                    m4.metric("Categories Compared", len(categories))
                    
                    st.markdown("### Stock Distribution")
                    # ✅ FIXED: Changed stock_df to stock_counts
                    stock_counts = filtered_df['stock_status'].value_counts().reset_index()
                    stock_counts.columns = ['Status', 'Count']
                    st.bar_chart(stock_counts.set_index('Status'), use_container_width=True)
                    
                # --- TAB 2: Price Differences ---
                with tab2:
                    st.header(f"💰 Price Differences ({site1} vs {site2})")
                    st.markdown(f"Positive difference means **{site1}** is more expensive. Negative means **{site2}** is more expensive.")
                    
                    # Keep only products present in both sites with valid prices
                    price_diff_df = filtered_df.dropna(subset=[f'{site1}_price', f'{site2}_price']).copy()
                    
                    # Add a formatted column for easier reading
                    price_diff_df['Price Difference (MAD)'] = price_diff_df['price_diff'].round(2)
                    
                    # Sort by biggest difference
                    price_diff_df = price_diff_df.sort_values(by='Price Difference (MAD)', ascending=False)
                    
                    display_cols = [
                        'reference', 'categorie', 
                        f'{site1}_name', f'{site1}_price', 
                        f'{site2}_name', f'{site2}_price', 
                        'Price Difference (MAD)'
                    ]
                    
                    st.dataframe(
                        price_diff_df[display_cols], 
                        use_container_width=True,
                        hide_index=True,
                        column_config={
                            f'{site1}_price': st.column_config.NumberColumn(format="%.2f MAD"),
                            f'{site2}_price': st.column_config.NumberColumn(format="%.2f MAD"),
                            'Price Difference (MAD)': st.column_config.NumberColumn(format="%.2f MAD"),
                        }
                    )
                    
                # --- TAB 3: Stock Differences ---
                with tab3:
                    st.header("📦 Stock Availability Differences")
                    st.markdown("Compare which store has items in stock when the other doesn't.")
                    
                    # Color coding for stock
                    def color_stock(val):
                        color = 'green' if val == 'In Stock' else 'red'
                        return f'color: {color}; font-weight: bold'
                    
                    display_cols_stock = [
                        'reference', 'categorie', 'stock_status',
                        f'{site1}_name', f'{site1}_stock',
                        f'{site2}_name', f'{site2}_stock'
                    ]
                    
                    # Show only items where stock status is different
                    stock_diff_df = filtered_df[
                        filtered_df['stock_status'].isin([
                            f"Only {site1} In Stock", 
                            f"Only {site2} In Stock",
                            "Both Out of Stock"
                        ])
                    ]
                    
                    # ✅ FIXED: Changed applymap to map for newer Pandas compatibility
                    st.dataframe(
                        stock_diff_df[display_cols_stock].style.map(color_stock, subset=[f'{site1}_stock', f'{site2}_stock']),
                        use_container_width=True,
                        hide_index=True
                    )
                    
                # --- TAB 4: Exclusives ---
                with tab4:
                    st.header("🗂️ Exclusive Products")
                    st.markdown("Products that exist only in one store and have no matching reference in the other.")
                    
                    col_ex1, col_ex2 = st.columns(2)
                    
                    with col_ex1:
                        st.subheader(f"Only in {site1}")
                        ex1 = filtered_df[filtered_df[f'{site2}_name'].isna()][[
                            'reference', 'categorie', f'{site1}_name', f'{site1}_price', f'{site1}_stock'
                        ]]
                        st.dataframe(ex1, use_container_width=True, hide_index=True)
                        
                    with col_ex2:
                        st.subheader(f"Only in {site2}")
                        ex2 = filtered_df[filtered_df[f'{site1}_name'].isna()][[
                            'reference', 'categorie', f'{site2}_name', f'{site2}_price', f'{site2}_stock'
                        ]]
                        st.dataframe(ex2, use_container_width=True, hide_index=True)

        except Exception as e:
            st.error(f"An error occurred while processing the files: {e}")
            st.info("Please ensure the uploaded files are the direct output of the scraper with columns: categorie, site, url_produit, product_name, reference, price, availability.")

else:
    st.info(f"👆 Please upload both {site1} and {site2} Excel files to begin.")